### ISSUE TITLE
可以编译一下可执行文件不？

### ISSUE THREAD

**Issue by cgisky1980** [csthenry/AutoUpdate#1]
顺便setting.ini 再加个参数  检测更新之后要运行的文件 或者命令

**Comment by csthenry** [comment]
编译后的文件我待会儿release。
更新之后所运行的程序在mainAppName处定义，暂不支持运行命令，后续可能会添加，当然你可以直接fork进行二开。

**Comment by csthenry** [comment]
已发布：https://github.com/csthenry/autoupdate-for-qt/releases/download/v1.1.4/updater.zip

**Comment by cgisky1980** [comment]
哈哈 感谢

**Comment by cgisky1980** [comment]
明白了，mainAppName 在服务器端。 看来我还是下个QT改一下，  这个流程  如果连不上网的话就卡在那了。
我觉得是不是应该这样，如果有更新，根据服务器端 mainAppName 决定后面要执行的命令
如果没有更新或者超时，执行 setting.ini 中定义的文件

**Comment by csthenry** [comment]
如果无法请求后端，那么也不会检测到更新，不存在卡住的情况。
你说的情况我没有理解，如果没有更新或者超时，那为什么需要执行文件或命令呢？毕竟检测更新这一流程肯定是从服务端返回最新版本号进行比较的，他的本质是更新器。

正确流程应该是：主程序自行检测更新->如果有更新->主程序拉起更新器（更新器会kill掉主程序，或主程序自行关闭）->更新器请求更新文件->增加/替换主程序目录所更新的文件->更新器启动主程序->完成更新。
